destination: ./_site
lsi:         false
port: 4000
pygments:    true
markdown:    rdiscount
url:         http://mapschool.io/
rdiscount:
  extensions: [smart]
language:
  en:
    feedback: 'feedback'
    contributors: 'contributors'
    tagline: 'a free introduction to geo'
    furtherreading: 'further reading'
    code: 'code'
    home: 'home'
  it:
    feedback: 'feedback'
    contributors: 'autori'
    tagline: 'una introduzione libera alla geografia'
    furtherreading: 'letture ulteriori'
    code: 'codice'
    home: 'pagina principale'
  es:
    feedback: 'contacto'
    contributors: 'autores'
    tagline: 'una introducci처n libre al mundo geo'
    furtherreading: 'lecturas adicionales'
    code: 'c처digo fuente'
    home: 'inicio'
  se:
    feedback: 'feedback'
    contributors: 'medarbetare'
    tagline: 'en fri introduktion till kartografi'
    furtherreading: 'vidare l채sning'
    code: 'k채llkod'
    home: 'startsidan'
