destination: ./_site
lsi:         false
port: 4000
pygments:    true
markdown:    rdiscount
url:         http://mapschool.io/
rdiscount:
  extensions: [smart]
language:
  en:
    feedback: 'feedback'
    contributors: 'contributors'
    tagline: 'a free introduction to geo'
    furtherreading: 'further reading'
    code: 'code'
    home: 'home'
  it:
    feedback: 'feedback'
    contributors: 'autori'
    tagline: 'una introduzione libera alla geografia'
    furtherreading: 'letture ulteriori'
    code: 'codice'
    home: 'pagina principale'
  es:
    feedback: 'contacto'
    contributors: 'autores'
    tagline: 'una introducción libre al mundo geo'
    furtherreading: 'lecturas adicionales'
    code: 'código fuente'
    home: 'inicio'
  se:
    feedback: 'feedback'
    contributors: 'medarbetare'
    tagline: 'en fri introduktion till kartografi'
    furtherreading: 'vidare läsning'
    code: 'källkod'
    home: 'startsidan'
  ja:
    feedback: 'フィードバック'
    contributors: '貢献者'
    tagline: '地理空間への招待状'
    furtherreading: '参考文献'
    code: 'コード'
    home: 'ホーム'
  pt:
    feedback: 'feedback'
    contributors: 'colaboradores'
    tagline: 'uma introdução gratuita à cartografia'
    furtherreading: 'leitura futura'
    code: 'código'
    home: 'página inicial'